repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: forbid-submodules
      - id: mixed-line-ending
  - repo: https://github.com/ansg191/pre-commit-rust
    rev: v1.1
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
