[advisories]
version = 2

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" }
]

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
