[package]
name = "trakt-rs"
version = "0.1.0"
edition = "2021"

[features]
default = ["rustls-tls"]

rustls-tls = ["oauth2/rustls-tls", "reqwest/rustls-tls"]
native-tls = ["oauth2/native-tls", "reqwest/native-tls"]

[dependencies]
bytes = "1.5.0"
form_urlencoded = "1.2.1"
http = "0.2.11"
itoa = "1.0.10"
oauth2 = { version = "4.4.2", default-features = false, features = ["reqwest"] }
percent-encoding = "2.3.1"
querystring = "1.1.0"
reqwest = { version = "0.11.24", default-features = false }
ryu = "1.0.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
thiserror = "1"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
trakt_macros = { path = "../trakt_macros" }
urlencoding = "2.1.3"

